import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, writeFileSync, symlinkSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const cli = fileURLToPath(new URL('../bin/agent-process-kit.mjs', import.meta.url));
const run = (project, command, extra = []) => spawnSync(process.execPath, [cli, command, '--project', project, ...extra], { encoding: 'utf8' });
const fixture = () => mkdtempSync(join(tmpdir(), 'kit setup '));
test('setup/rollback preserve unrelated files and require apply', () => {
  const project = fixture();
  writeFileSync(join(project, 'AGENTS.md'), 'operator instructions');
  assert.equal(run(project, 'setup').status, 0);
  const owned = join(project, '.agent-process-kit');
  assert.equal(existsSync(owned), false);
  const installed = run(project, 'setup', ['--apply']);
  assert.equal(installed.status, 0, installed.stderr);
  assert.equal(readFileSync(join(project, 'AGENTS.md'), 'utf8'), 'operator instructions');
  const instructions = readFileSync(join(owned, 'INSTRUCTIONS.md'), 'utf8');
  assert.match(instructions, /docs\/how-it-works\.md/);
  assert.doesNotMatch(instructions, /docs\/workflow\.md/);
  writeFileSync(join(owned, 'my-note.txt'), 'keep');
  assert.equal(run(project, 'rollback').status, 0);
  assert.equal(existsSync(join(owned, 'INSTRUCTIONS.md')), true);
  const result = run(project, 'rollback', ['--apply']);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(existsSync(join(owned, 'INSTRUCTIONS.md')), false);
  assert.equal(readFileSync(join(owned, 'my-note.txt'), 'utf8'), 'keep');
});
test('rollback refuses edited owned files before deleting anything', () => {
  const project = fixture();
  assert.equal(run(project, 'setup', ['--apply']).status, 0);
  const owned = join(project, '.agent-process-kit');
  writeFileSync(join(owned, 'INSTRUCTIONS.md'), 'human edits');
  assert.equal(run(project, 'rollback', ['--apply']).status, 2);
  assert.equal(existsSync(join(owned, 'hooks.example.json')), true);
  assert.equal(readFileSync(join(owned, 'INSTRUCTIONS.md'), 'utf8'), 'human edits');
});
test('existing/symlink destinations and forged receipt paths are refused', () => {
  const project = fixture(), outside = fixture();
  symlinkSync(outside, join(project, '.agent-process-kit'));
  assert.equal(run(project, 'setup', ['--apply']).status, 2);
  assert.equal(existsSync(join(outside, 'receipt.json')), false);
  const second = fixture();
  assert.equal(run(second, 'setup', ['--apply']).status, 0);
  const receipt = join(second, '.agent-process-kit', 'receipt.json');
  const parsed = JSON.parse(readFileSync(receipt, 'utf8'));
  parsed.files[0].path = '../AGENTS.md';
  writeFileSync(receipt, JSON.stringify(parsed));
  assert.equal(run(second, 'rollback', ['--apply']).status, 2);
});
test('partial prepared setup can be rolled back, missing files are not fabricated', () => {
  const project = fixture();
  assert.equal(run(project, 'setup', ['--apply']).status, 0);
  const owned = join(project, '.agent-process-kit');
  const receipt = join(owned, 'receipt.json');
  const parsed = JSON.parse(readFileSync(receipt, 'utf8'));
  parsed.phase = 'prepared';
  writeFileSync(receipt, JSON.stringify(parsed));
  unlinkSync(join(owned, 'hooks.example.json'));
  assert.equal(run(project, 'rollback', ['--apply']).status, 0);
  assert.equal(existsSync(join(owned, 'receipt.json')), false);
});
